services:
  api1:
    build:
      context: .
      target: api
    environment:
      - SOCK=/run/sock/api1.sock
    volumes:
      - sock:/run/sock
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160M"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    security_opt:
      - seccomp:unconfined

  api2:
    build:
      context: .
      target: api
    environment:
      - SOCK=/run/sock/api2.sock
    volumes:
      - sock:/run/sock
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160M"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    security_opt:
      - seccomp:unconfined

  lb:
    build:
      context: .
      target: proxy
    restart: always
    depends_on:
      - api1
      - api2
    environment:
      - UPSTREAMS=/run/sock/api1.sock,/run/sock/api2.sock
      - PORT=9999
      - WORKERS=1
    ports:
      - "9999:9999"
    volumes:
      - sock:/run/sock
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30M"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    security_opt:
      - seccomp:unconfined

volumes:
  sock:
